### PR TITLE
Fix memory issues

### PR DESCRIPTION
**Pull request by ppolxda**
1. Fix memory issues Not close page When PageCoroutine timeout or exception
2. Add PYPPETEER_PAGE_COROUTINE_TIMEOUT to set waitForXPath、waitForRequest Timeout

### CODE REVIEW

**Comment by elacuesta** [comment]
Hey @ppolxda, sorry for taking so long to reply. I think the idea is good, but the CI checks are failing. I changed a few things in [this branch](https://github.com/elacuesta/scrapy-pyppeteer/commits/pagecoroutine-timeout-by-ppolxda), if you could [enable edits by maintainers](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork) we can both continue to work on it. Thanks!

**Comment by nichoi** [comment]
Any updates regarding this?

**Comment by ppolxda** [comment]
> Any updates regarding this?

Not updates for [this branch](https://github.com/elacuesta/scrapy-pyppeteer/commits/pagecoroutine-timeout-by-ppolxda)
I think it was ok.

**Comment by elacuesta** [comment]
Released as part of [`0.0.12`](https://github.com/elacuesta/scrapy-pyppeteer/releases/tag/v0.0.12), many thanks @ppolxda!

**Pull request merged**
